# Generated by Django 6.0.5 on 2026-06-01 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('valid_term_months', models.IntegerField()),
                ('units_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CertificationVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(blank=True, max_length=50, null=True)),
                ('eff_date', models.DateField()),
                ('cert_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='skillflow.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='certification',
            name='vendor_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='skillflow.certificationvendor'),
        ),
        migrations.CreateModel(
            name='ContinuingEducationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('presenter', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='ce_certificates/')),
                ('applicable_certs', models.ManyToManyField(to='skillflow.certificationrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
